"""Corpus ingestion for Aquinas grounding retrieval.

Reads corpus/sources.yaml, fetches confirmed-public-domain sources, cleans
and chunks them, embeds each chunk with the same MiniLM provider used for
Insight Tree relatedness, and stores everything in a persistent Chroma
collection under data/corpus/index. Raw downloaded text and the index are
gitignored (data/ as a whole is already excluded) and are regenerated by
re-running this script rather than being checked in.

Every fetch is logged to data/corpus/retrieval_log.json with the exact URL
used, retrieval timestamp, and a content hash, so "confirmed_pd in the
manifest" is backed by "here is what we actually downloaded" rather than
memory alone.

Usage:
    aquinas_env/bin/python ingest_corpus.py --ids web-bible didache aristotle-nicomachean-ethics
    aquinas_env/bin/python ingest_corpus.py --all-confirmed
"""

from __future__ import annotations

import argparse
import hashlib
import html
import io
import json
import re
import sys
import time
import zipfile
from dataclasses import dataclass
from datetime import datetime, timezone
from html.parser import HTMLParser
from pathlib import Path
from urllib.error import HTTPError
from urllib.parse import quote
from urllib.request import Request, urlopen

import chromadb
import yaml

from relatedness import MiniLMRelatednessProvider

BACKEND_ROOT = Path(__file__).resolve().parent
MANIFEST_PATH = BACKEND_ROOT / "corpus" / "sources.yaml"
RAW_DIR = BACKEND_ROOT / "data" / "corpus" / "raw"
INDEX_DIR = BACKEND_ROOT / "data" / "corpus" / "index"
RETRIEVAL_LOG_PATH = BACKEND_ROOT / "data" / "corpus" / "retrieval_log.json"

USER_AGENT = "AquinasCorpusIngestion/1.0 (research; contact: rbaltodano337@gmail.com)"
CHUNK_TARGET_WORDS = 200
CHUNK_MAX_WORDS = 320

ROMAN_ISH_ORDER = [
    "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine",
    "Ten", "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen",
]


@dataclass
class FetchResult:
    text: str
    source_url: str


class _TextExtractor(HTMLParser):
    """Minimal HTML-to-text extractor: drops script/style, keeps block text."""

    _SKIP_TAGS = {"script", "style", "nav", "header", "footer"}
    _BLOCK_TAGS = {"p", "div", "br", "li", "h1", "h2", "h3", "h4", "tr"}

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self._skip_depth = 0
        self._chunks: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag in self._SKIP_TAGS:
            self._skip_depth += 1
        elif tag in self._BLOCK_TAGS:
            self._chunks.append("\n")

    def handle_endtag(self, tag: str) -> None:
        if tag in self._SKIP_TAGS and self._skip_depth > 0:
            self._skip_depth -= 1

    def handle_data(self, data: str) -> None:
        if self._skip_depth == 0 and data.strip():
            self._chunks.append(data)

    def text(self) -> str:
        return "".join(self._chunks)


def _http_get(url: str, timeout: int = 30, retries: int = 4) -> bytes:
    request = Request(url, headers={"User-Agent": USER_AGENT})
    last_error: Exception | None = None
    for attempt in range(retries):
        try:
            with urlopen(request, timeout=timeout) as response:
                return response.read()
        except HTTPError as exc:
            last_error = exc
            if exc.code == 429 or exc.code >= 500:
                wait_seconds = 5 * (attempt + 1)
                print(f"  ({exc.code} from {url}; retrying in {wait_seconds}s)")
                time.sleep(wait_seconds)
                continue
            raise
    raise RuntimeError(f"Giving up on {url} after {retries} attempts") from last_error


def _strip_html(raw_html: str) -> str:
    extractor = _TextExtractor()
    extractor.feed(raw_html)
    text = html.unescape(extractor.text())
    lines = [line.strip() for line in text.splitlines()]
    lines = [line for line in lines if line]
    return "\n\n".join(lines)


_REDIRECT_PATTERN = re.compile(r"^Redirect to:\s*\n*(.+)$", re.MULTILINE)


def _wikisource_extract(title: str, _redirects_followed: int = 0) -> str | None:
    # TextExtracts (prop=extracts) returns empty for pages built with the
    # ProofreadPage <pages> transclusion extension, which is how most
    # Wikisource works are assembled. Rendered HTML via action=parse works
    # for both transcluded and plain pages, so use that unconditionally.
    api_url = (
        "https://en.wikisource.org/w/api.php?action=parse"
        f"&page={quote(title, safe='')}&prop=text&format=json"
    )
    payload = json.loads(_http_get(api_url))
    raw_html = payload.get("parse", {}).get("text", {}).get("*", "")
    if not raw_html.strip():
        return None
    text = _strip_html(raw_html)
    if not text.strip():
        return None

    redirect_match = _REDIRECT_PATTERN.match(text.strip())
    if redirect_match and _redirects_followed < 3:
        target = redirect_match.group(1).strip()
        return _wikisource_extract(target, _redirects_followed + 1)

    return text


def _wikisource_subpages(title_prefix: str) -> list[str]:
    api_url = (
        "https://en.wikisource.org/w/api.php?action=query&list=allpages"
        f"&apprefix={quote(title_prefix, safe='')}&aplimit=50&format=json"
    )
    payload = json.loads(_http_get(api_url))
    titles = [page["title"] for page in payload.get("query", {}).get("allpages", [])]
    # The API normalizes underscores to spaces in returned titles, so compare
    # on the normalized form rather than the raw (possibly underscored) prefix.
    normalized_prefix = title_prefix.replace("_", " ")
    subpages = [
        t for t in titles
        if t != normalized_prefix and t.startswith(normalized_prefix + "/")
    ]

    def sort_key(title: str) -> int:
        suffix = title.rsplit("/", 1)[-1]
        for word in suffix.split():
            if word in ROMAN_ISH_ORDER:
                return ROMAN_ISH_ORDER.index(word)
        return len(ROMAN_ISH_ORDER) + 1

    return sorted(subpages, key=sort_key)


def fetch_wikisource(url: str) -> FetchResult:
    title = url.rsplit("/wiki/", 1)[-1]
    subpages = _wikisource_subpages(title)
    if subpages:
        parts = []
        for subpage_title in subpages:
            extract = _wikisource_extract(subpage_title)
            if extract:
                parts.append(f"[{subpage_title}]\n{extract}")
            time.sleep(1)
        if parts:
            return FetchResult(text="\n\n".join(parts), source_url=url)

    extract = _wikisource_extract(title)
    if extract:
        return FetchResult(text=extract, source_url=url)

    raise RuntimeError(f"No extractable text found for Wikisource title {title!r}")


def fetch_ebible_web(url: str) -> FetchResult:
    zip_url = "https://ebible.org/Scriptures/eng-web_html.zip"
    raw_zip = _http_get(zip_url, timeout=60)
    parts = []
    with zipfile.ZipFile(io.BytesIO(raw_zip)) as archive:
        names = sorted(n for n in archive.namelist() if n.upper().endswith(".HTM"))
        for name in names:
            raw_html = archive.read(name).decode("utf-8", errors="replace")
            text = _strip_html(raw_html)
            if text.strip():
                book_ref = Path(name).stem
                parts.append(f"[{book_ref}]\n{text}")
    return FetchResult(text="\n\n".join(parts), source_url=zip_url)


_NEWADVENT_CHAPTER_LINK = re.compile(r'href="(?:\.\./fathers/)?(\d+)\.htm"')


def fetch_newadvent(url: str) -> FetchResult:
    """New Advent Church Fathers pages come in two shapes: a short work is a
    single page with the text inline; a long multi-book work (e.g.
    Confessions, City of God) is a table-of-contents page whose real content
    lives on separate per-chapter pages named <base><NN>.htm. Crawl those
    when present; otherwise treat the page itself as the content."""
    base_id = Path(url).stem  # e.g. "1101" from ".../fathers/1101.htm"
    raw_html = _http_get(url).decode("utf-8", errors="replace")

    chapter_numbers = sorted(
        {
            int(match)
            for match in _NEWADVENT_CHAPTER_LINK.findall(raw_html)
            if match.startswith(base_id) and match != base_id
        }
    )

    if not chapter_numbers:
        return FetchResult(text=_strip_html(raw_html), source_url=url)

    base_url = url.rsplit("/", 1)[0]
    parts = []
    for chapter_number in chapter_numbers:
        chapter_url = f"{base_url}/{chapter_number}.htm"
        chapter_html = _http_get(chapter_url).decode("utf-8", errors="replace")
        text = _strip_html(chapter_html)
        if text.strip():
            parts.append(f"[{chapter_number}]\n{text}")
        time.sleep(0.5)

    return FetchResult(text="\n\n".join(parts), source_url=url)


def fetch_generic_html(url: str) -> FetchResult:
    raw_html = _http_get(url).decode("utf-8", errors="replace")
    text = _strip_html(raw_html)
    return FetchResult(text=text, source_url=url)


def fetch_local_file(local_path: str) -> FetchResult:
    path = (BACKEND_ROOT / local_path).resolve()
    if not path.is_file():
        raise RuntimeError(f"Local source file not found: {path}")
    text = path.read_text(encoding="utf-8", errors="replace")
    return FetchResult(text=text, source_url=f"file://{path}")


def fetch_source(source: dict) -> FetchResult:
    local_path = source.get("local_path")
    if local_path:
        return fetch_local_file(local_path)

    url = source.get("url")
    if not url:
        raise RuntimeError(f"Source {source['id']!r} has no url or local_path to fetch.")

    if "ebible.org" in url:
        return fetch_ebible_web(url)
    if "wikisource.org/wiki/" in url:
        return fetch_wikisource(url)
    if "newadvent.org/fathers/" in url:
        return fetch_newadvent(url)
    return fetch_generic_html(url)


_DIGIT_NAV_RUN = re.compile(r"(?:\b\d{1,3}\b\s+){4,}\d{1,3}\b")
_BREADCRUMB_LINE = re.compile(r"^(Home\s*>\s*.+|.+\s*>\s*.+\s*>\s*.+)$")


def _clean_navigation_noise(text: str) -> str:
    """Strip common site-chrome artifacts that survive HTML stripping:
    chapter-number nav lists, breadcrumbs, and prev/next arrow links. These
    are structural chrome, not content, so removing them is safe rather than
    lossy."""
    text = _DIGIT_NAV_RUN.sub(" ", text)

    cleaned_lines = []
    previous_line = None
    for line in text.splitlines():
        stripped = line.strip()
        if _BREADCRUMB_LINE.match(stripped) or "←" in stripped or "→" in stripped:
            continue
        if stripped and stripped == previous_line:
            continue
        cleaned_lines.append(line)
        previous_line = stripped

    return "\n".join(cleaned_lines)


def chunk_text(text: str) -> list[str]:
    paragraphs = [p.strip() for p in re.split(r"\n\s*\n", text) if p.strip()]
    chunks: list[str] = []
    current_words: list[str] = []

    def flush() -> None:
        if current_words:
            chunks.append(" ".join(current_words))
            current_words.clear()

    for paragraph in paragraphs:
        # `[Title/Book N]`-style markers (inserted by fetch_wikisource,
        # fetch_ebible_web, fetch_newadvent to tag each subpage/chapter) mark
        # the start of a new source section. Force a boundary here so a
        # section's opening marker/header text never gets merged onto the
        # tail of the *previous* section's chunk — that bleed previously let
        # e.g. a Book 7 passage absorb a trailing "Book 8" marker and get
        # mis-cited by the model, which just reads whatever label is nearest
        # in the retrieved text.
        if paragraph.startswith("["):
            flush()
        words = paragraph.split()
        if len(words) > CHUNK_MAX_WORDS:
            flush()
            for i in range(0, len(words), CHUNK_TARGET_WORDS):
                chunks.append(" ".join(words[i:i + CHUNK_TARGET_WORDS]))
            continue

        if len(current_words) + len(words) > CHUNK_MAX_WORDS:
            flush()
        current_words.extend(words)
        if len(current_words) >= CHUNK_TARGET_WORDS:
            flush()

    flush()
    return chunks


def load_manifest() -> list[dict]:
    with MANIFEST_PATH.open() as f:
        data = yaml.safe_load(f)
    return data["sources"]


def load_retrieval_log() -> dict:
    if RETRIEVAL_LOG_PATH.exists():
        with RETRIEVAL_LOG_PATH.open() as f:
            return json.load(f)
    return {}


def save_retrieval_log(log: dict) -> None:
    RETRIEVAL_LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    with RETRIEVAL_LOG_PATH.open("w") as f:
        json.dump(log, f, indent=2, sort_keys=True)


def ingest_source(
    source: dict,
    collection: "chromadb.Collection",
    embedder: MiniLMRelatednessProvider,
    retrieval_log: dict,
) -> None:
    source_id = source["id"]
    print(f"[{source_id}] fetching...")
    result = fetch_source(source)
    text = _clean_navigation_noise(result.text).strip()
    if not text:
        raise RuntimeError(f"Fetched empty text for {source_id!r}; check the fetcher/URL.")

    RAW_DIR.mkdir(parents=True, exist_ok=True)
    raw_path = RAW_DIR / f"{source_id}.txt"
    raw_path.write_text(text, encoding="utf-8")

    content_hash = hashlib.sha256(text.encode("utf-8")).hexdigest()
    retrieval_log[source_id] = {
        "title": source["title"],
        "source_url": result.source_url,
        "retrieved_at": datetime.now(timezone.utc).isoformat(),
        "sha256": content_hash,
        "char_count": len(text),
    }

    chunks = chunk_text(text)
    print(f"[{source_id}] {len(text)} chars -> {len(chunks)} chunks; embedding...")

    existing = collection.get(where={"source_id": source_id}, include=[])
    if existing["ids"]:
        collection.delete(ids=existing["ids"])

    batch_size = 64
    for start in range(0, len(chunks), batch_size):
        batch = chunks[start:start + batch_size]
        embeddings = embedder.embed_many(batch)
        ids = [f"{source_id}::{start + i}" for i in range(len(batch))]
        metadatas = [
            {
                "source_id": source_id,
                "title": source["title"],
                "category": source["category"],
                "license_status": source["license_status"],
                "chunk_index": start + i,
            }
            for i in range(len(batch))
        ]
        collection.add(
            ids=ids,
            documents=batch,
            embeddings=embeddings.tolist(),
            metadatas=metadatas,
        )

    print(f"[{source_id}] done ({len(chunks)} chunks indexed).")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ids", nargs="+", help="Specific source ids to ingest.")
    parser.add_argument(
        "--all-confirmed",
        action="store_true",
        help="Ingest every source with license_status: confirmed_pd.",
    )
    args = parser.parse_args()

    if not args.ids and not args.all_confirmed:
        parser.error("Pass --ids <id...> or --all-confirmed.")

    sources = load_manifest()
    by_id = {s["id"]: s for s in sources}

    if args.all_confirmed:
        selected = [s for s in sources if s["license_status"] == "confirmed_pd"]
    else:
        selected = []
        for source_id in args.ids:
            if source_id not in by_id:
                sys.exit(f"Unknown source id: {source_id!r}")
            source = by_id[source_id]
            if source["license_status"] != "confirmed_pd":
                sys.exit(
                    f"Refusing to ingest {source_id!r}: license_status is "
                    f"{source['license_status']!r}, not confirmed_pd."
                )
            selected.append(source)

    INDEX_DIR.mkdir(parents=True, exist_ok=True)
    client = chromadb.PersistentClient(path=str(INDEX_DIR))
    collection = client.get_or_create_collection("aquinas_grounding")

    embedder = MiniLMRelatednessProvider()
    embedder.load()

    retrieval_log = load_retrieval_log()

    for source in selected:
        try:
            ingest_source(source, collection, embedder, retrieval_log)
        except Exception as exc:  # noqa: BLE001 - surface and continue with the rest
            print(f"[{source['id']}] FAILED: {exc}")
        finally:
            save_retrieval_log(retrieval_log)

    print(f"\nCollection now has {collection.count()} chunks total.")


if __name__ == "__main__":
    main()
